"use client";

import { useState } from "react";
import { Card, Button, Tag } from "@/components/ui";
import {
  FileText,
  ArrowLeft,
  Copy,
  Check,
  AlertTriangle,
  BookOpen,
  Scale,
  Quote,
  Link2,
  Loader2,
} from "lucide-react";
import Link from "next/link";

interface CaseBrief {
  caseName: string;
  citation: string;
  court: string;
  year: string;
  facts: string;
  issue: string;
  held: string;
  ratioDecidendi: string;
  obiterDicta: string;
  application: string;
  significance: string;
  keyQuotes: string[];
  relatedCases: string[];
}

export default function CaseBriefPage() {
  const [caseName, setCaseName] = useState("");
  const [citation, setCitation] = useState("");
  const [caseText, setCaseText] = useState("");
  const [brief, setBrief] = useState<CaseBrief | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  // TODO: Replace with useAction(api.ai.caseBrief.generate) when Convex is wired
  const handleGenerate = async () => {
    if (!caseName.trim()) return;
    setLoading(true);
    setBrief(null);

    // Simulated delay for demo — replace with actual Convex action call
    await new Promise((r) => setTimeout(r, 2000));

    setBrief({
      caseName: caseName,
      citation: citation || "[Year] UKSC / EWCA Civ",
      court: "Supreme Court / Court of Appeal",
      year: "20XX",
      facts:
        "The key material facts of the case involve a dispute regarding the interpretation and application of established legal principles. The claimant brought an action seeking declaratory relief and damages arising from the defendant's alleged breach of duty.",
      issue:
        "Whether the established common law principle extends to cover the specific factual circumstances presented, and if so, what remedies are available to the injured party.",
      held:
        "The court held that the principle does extend to cover these circumstances. The appeal was allowed and the matter remitted for further consideration of quantum.",
      ratioDecidendi:
        "The binding principle established is that the duty of care extends to foreseeable consequences arising from the defendant's conduct, provided there exists sufficient proximity between the parties and it is fair, just, and reasonable to impose such a duty.",
      obiterDicta:
        "Lord/Lady Justice remarked that in different factual circumstances, such as where the harm was purely economic, the analysis might differ. This observation was not necessary for the decision but may influence future cases.",
      application:
        "This case has been applied in subsequent decisions to extend the scope of liability in analogous situations. It has been distinguished where the factual matrix differs materially.",
      significance:
        "This case is significant for UK law students as it clarifies the test applicable in this area of law and provides authoritative guidance on the scope of the relevant duty. It is frequently cited in mooting and examination contexts.",
      keyQuotes: [
        '"The law must develop incrementally, by analogy with established categories."',
        '"It is not enough to show that harm was foreseeable; the claimant must also demonstrate proximity and that it is fair, just and reasonable to impose a duty."',
      ],
      relatedCases: [
        "Donoghue v Stevenson [1932] AC 562 — foundational duty of care",
        "Caparo Industries plc v Dickman [1990] 2 AC 605 — three-stage test",
        "Robinson v Chief Constable [2018] UKSC 4 — incremental approach",
      ],
    });

    setLoading(false);
  };

  const handleCopy = () => {
    if (!brief) return;
    const text = `CASE BRIEF: ${brief.caseName}
Citation: ${brief.citation}
Court: ${brief.court} (${brief.year})

FACTS
${brief.facts}

ISSUE
${brief.issue}

HELD
${brief.held}

RATIO DECIDENDI
${brief.ratioDecidendi}

OBITER DICTA
${brief.obiterDicta}

APPLICATION
${brief.application}

SIGNIFICANCE
${brief.significance}

KEY QUOTES
${brief.keyQuotes.map((q) => `- ${q}`).join("\n")}

RELATED CASES
${brief.relatedCases.map((c) => `- ${c}`).join("\n")}

---
Generated by Ratio. AI-generated analysis — always verify against primary sources.`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="pb-6 md:max-w-content-narrow mx-auto">
      {/* Header */}
      <div className="px-4 md:px-6 lg:px-8 pt-3 pb-4">
        <Link
          href="/tools"
          className="flex items-center gap-1.5 text-court-text-sec text-xs mb-3 hover:text-court-text transition-colors"
        >
          <ArrowLeft size={14} />
          Back to Tools
        </Link>
        <div className="flex items-center gap-2 mb-1">
          <FileText size={20} className="text-blue-400" />
          <h1 className="font-serif text-2xl font-bold text-court-text">
            Case Brief Generator
          </h1>
        </div>
        <p className="text-xs text-court-text-sec mt-1">
          Generate structured IRAC case briefs from case names or pasted text
        </p>
      </div>

      {/* Input Section */}
      <section className="px-4 md:px-6 lg:px-8 mb-4">
        <Card className="p-5">
          <div className="space-y-4">
            {/* Case Name */}
            <div>
              <label className="block text-xs font-bold text-court-text-sec tracking-wider mb-1.5">
                CASE NAME *
              </label>
              <input
                type="text"
                value={caseName}
                onChange={(e) => setCaseName(e.target.value)}
                placeholder="e.g. Donoghue v Stevenson"
                className="w-full bg-navy-mid border border-court-border rounded-xl px-3.5 py-2.5 text-court-base text-court-text outline-none focus:border-gold/40 placeholder:text-court-text-ter"
              />
            </div>

            {/* Citation */}
            <div>
              <label className="block text-xs font-bold text-court-text-sec tracking-wider mb-1.5">
                CITATION (OPTIONAL)
              </label>
              <input
                type="text"
                value={citation}
                onChange={(e) => setCitation(e.target.value)}
                placeholder="e.g. [1932] AC 562"
                className="w-full bg-navy-mid border border-court-border rounded-xl px-3.5 py-2.5 text-court-base text-court-text outline-none focus:border-gold/40 placeholder:text-court-text-ter"
              />
            </div>

            {/* Case Text */}
            <div>
              <label className="block text-xs font-bold text-court-text-sec tracking-wider mb-1.5">
                CASE NOTES / TEXT (OPTIONAL)
              </label>
              <textarea
                value={caseText}
                onChange={(e) => setCaseText(e.target.value)}
                placeholder="Paste case text, judgment excerpts, or your own notes to improve the brief quality..."
                rows={5}
                className="w-full bg-navy-mid border border-court-border rounded-xl px-3.5 py-2.5 text-court-base text-court-text outline-none focus:border-gold/40 placeholder:text-court-text-ter resize-none"
              />
            </div>

            <Button
              onClick={handleGenerate}
              disabled={!caseName.trim() || loading}
              fullWidth
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <Loader2 size={16} className="animate-spin" />
                  Generating Brief...
                </span>
              ) : (
                "Generate Case Brief"
              )}
            </Button>
          </div>
        </Card>
      </section>

      {/* Disclaimer */}
      <section className="px-4 md:px-6 lg:px-8 mb-4">
        <div className="flex items-start gap-2 px-3 py-2 rounded-xl bg-orange-400/5 border border-orange-400/10">
          <AlertTriangle size={14} className="text-orange-400 shrink-0 mt-0.5" />
          <p className="text-court-xs text-orange-400/80">
            AI-generated analysis. Always verify against primary sources. This
            tool is for study purposes only and does not constitute legal advice.
          </p>
        </div>
      </section>

      {/* Results */}
      {brief && (
        <section className="px-4 md:px-6 lg:px-8 space-y-3">
          {/* Header Card */}
          <Card className="p-5" highlight>
            <div className="flex justify-between items-start mb-3">
              <div>
                <h2 className="font-serif text-lg font-bold text-court-text">
                  {brief.caseName}
                </h2>
                <p className="text-court-sm text-court-text-ter mt-0.5">
                  {brief.citation} · {brief.court} · {brief.year}
                </p>
              </div>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-court-xs font-semibold text-court-text-sec hover:text-gold hover:bg-gold-dim transition-all"
              >
                {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
                {copied ? "Copied" : "Copy"}
              </button>
            </div>
            <Tag color="blue" small>IRAC Brief</Tag>
          </Card>

          {/* Facts */}
          <BriefSection icon={<BookOpen size={16} />} title="Facts" content={brief.facts} />

          {/* Issue */}
          <BriefSection icon={<AlertTriangle size={16} />} title="Issue" content={brief.issue} />

          {/* Held */}
          <BriefSection icon={<Scale size={16} />} title="Held" content={brief.held} />

          {/* Ratio Decidendi */}
          <BriefSection
            icon={<FileText size={16} />}
            title="Ratio Decidendi"
            content={brief.ratioDecidendi}
            highlight
          />

          {/* Obiter Dicta */}
          <BriefSection
            icon={<Quote size={16} />}
            title="Obiter Dicta"
            content={brief.obiterDicta}
          />

          {/* Application */}
          <BriefSection
            icon={<Link2 size={16} />}
            title="Application"
            content={brief.application}
          />

          {/* Significance */}
          <BriefSection
            icon={<Scale size={16} />}
            title="Significance"
            content={brief.significance}
          />

          {/* Key Quotes */}
          {brief.keyQuotes.length > 0 && (
            <Card className="p-4">
              <div className="flex items-center gap-2 mb-3">
                <Quote size={16} className="text-gold" />
                <h3 className="text-court-base font-bold text-court-text">Key Quotes</h3>
              </div>
              <div className="space-y-2">
                {brief.keyQuotes.map((q, i) => (
                  <div
                    key={i}
                    className="pl-3 border-l-2 border-gold/30 text-court-sm text-court-text-sec italic"
                  >
                    {q}
                  </div>
                ))}
              </div>
            </Card>
          )}

          {/* Related Cases */}
          {brief.relatedCases.length > 0 && (
            <Card className="p-4">
              <div className="flex items-center gap-2 mb-3">
                <Link2 size={16} className="text-blue-400" />
                <h3 className="text-court-base font-bold text-court-text">Related Cases</h3>
              </div>
              <div className="space-y-1.5">
                {brief.relatedCases.map((c, i) => (
                  <p key={i} className="text-court-sm text-court-text-sec">
                    {c}
                  </p>
                ))}
              </div>
            </Card>
          )}
        </section>
      )}
    </div>
  );
}

function BriefSection({
  icon,
  title,
  content,
  highlight = false,
}: {
  icon: React.ReactNode;
  title: string;
  content: string;
  highlight?: boolean;
}) {
  return (
    <Card className={`p-4 ${highlight ? "border-gold/20" : ""}`}>
      <div className="flex items-center gap-2 mb-2">
        <span className={highlight ? "text-gold" : "text-court-text-ter"}>{icon}</span>
        <h3 className="text-court-base font-bold text-court-text">{title}</h3>
      </div>
      <p className="text-court-sm text-court-text-sec leading-relaxed">{content}</p>
    </Card>
  );
}
