"use client";

import { Info } from "lucide-react";

interface AIDisclaimerProps {
  /** "compact" = single-line for session screens, "full" = expanded for feedback pages */
  variant?: "compact" | "full";
  className?: string;
}

/**
 * Disclaimer shown wherever AI-generated feedback or judicial responses appear.
 *
 * Why this exists: Users and educators rightly expect transparency about
 * AI-generated content. This makes clear that RATIO is an educational
 * practice tool — not a substitute for qualified legal guidance.
 */
export function AIDisclaimer({ variant = "compact", className = "" }: AIDisclaimerProps) {
  if (variant === "compact") {
    return (
      <p className={`flex items-center gap-1.5 text-court-xs text-court-text-ter ${className}`}>
        <Info size={12} className="shrink-0" />
        AI-generated feedback for educational practice only — not legal advice.
      </p>
    );
  }

  return (
    <div className={`rounded-xl border border-court-border-light bg-white/[0.02] p-4 ${className}`}>
      <div className="flex gap-2.5 items-start">
        <Info size={16} className="text-gold shrink-0 mt-0.5" />
        <div>
          <p className="text-court-sm font-semibold text-court-text-sec mb-1">
            AI-Generated Feedback
          </p>
          <p className="text-court-xs text-court-text-ter leading-relaxed">
            All scores, feedback, and judicial responses on RATIO are generated by AI for
            educational practice purposes. They are designed to help you develop advocacy
            skills but do not constitute legal advice and have not been reviewed by a
            qualified legal professional. Always consult a qualified lawyer, tutor, or
            supervisor for authoritative legal guidance.
          </p>
        </div>
      </div>
    </div>
  );
}
