"use client";

import { Info } from "lucide-react";

interface AIDisclaimerProps {
  /** "compact" = single-line for session screens, "full" = expanded for feedback pages */
  variant?: "compact" | "full";
  className?: string;
}

/**
 * Disclaimer shown wherever AI-generated feedback or judicial responses appear.
 *
 * Tone: reassuring and transparent. Positions AI feedback as a valuable
 * training tool grounded in real legal sources, while maintaining
 * clear boundaries around professional legal advice.
 */
export function AIDisclaimer({ variant = "compact", className = "" }: AIDisclaimerProps) {
  if (variant === "compact") {
    return (
      <p className={`flex items-center gap-1.5 text-court-xs text-court-text-ter ${className}`}>
        <Info size={12} className="shrink-0" />
        AI-powered training feedback · sourced from UK legal databases.
      </p>
    );
  }

  return (
    <div className={`rounded-xl border border-court-border-light bg-white/[0.02] p-4 ${className}`}>
      <div className="flex gap-2.5 items-start">
        <Info size={16} className="text-gold shrink-0 mt-0.5" />
        <div>
          <p className="text-court-sm font-semibold text-court-text-sec mb-1">
            About This Feedback
          </p>
          <p className="text-court-xs text-court-text-ter leading-relaxed">
            Scores, feedback, and judicial responses on RATIO are generated by AI
            trained on authoritative UK legal sources. They are designed to develop
            your advocacy and analytical skills to a professional standard. As with
            all legal training, we encourage you to verify citations against primary
            sources and consult your tutor or supervisor for authoritative guidance.
          </p>
        </div>
      </div>
    </div>
  );
}
