"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { BookOpen, X, Download, Copy, Check, Loader2, FileText } from "lucide-react";

interface CaseNote {
  caseName: string;
  citation: string;
  court: string;
  areaOfLaw: string;
  parties: { appellant: string; respondent: string };
  legalIssues: string[];
  argumentsFor: string[];
  argumentsAgainst: string[];
  authoritiesCited: { name: string; point: string }[];
  keyPrinciples: string[];
  outcome: string;
  studentNotes: string;
}

interface CaseNotePanelProps {
  caseNote: CaseNote | null;
  isGenerating: boolean;
  onGenerate: () => void;
  error: string | null;
}

/**
 * Case Note Panel — shows AI-generated structured case notes
 * formatted like a law student's revision notes.
 * Can be copied or downloaded as a .txt file.
 */
export default function CaseNotePanel({
  caseNote,
  isGenerating,
  onGenerate,
  error,
}: CaseNotePanelProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateTextVersion = (note: CaseNote): string => {
    const lines = [
      "═══════════════════════════════════════════════════════",
      "                    CASE NOTE",
      "        Ratio — The Digital Court Society",
      "═══════════════════════════════════════════════════════",
      "",
      `Case:       ${note.caseName}`,
      `Citation:   ${note.citation}`,
      `Court:      ${note.court}`,
      `Area:       ${note.areaOfLaw}`,
      `Date:       ${new Date().toLocaleDateString("en-GB", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}`,
      "",
      "───────────────────────────────────────────────────────",
      "",
      "PARTIES",
      `  Appellant/Claimant:  ${note.parties.appellant}`,
      `  Respondent/Defendant: ${note.parties.respondent}`,
      "",
      "LEGAL ISSUES",
      ...note.legalIssues.map((issue, i) => `  ${i + 1}. ${issue}`),
      "",
      "ARGUMENTS FOR (Counsel's submissions)",
      ...note.argumentsFor.map((arg, i) => `  ${i + 1}. ${arg}`),
      "",
      "ARGUMENTS AGAINST (Counter-arguments raised)",
      ...note.argumentsAgainst.map((arg, i) => `  ${i + 1}. ${arg}`),
      "",
      "AUTHORITIES CITED",
      ...note.authoritiesCited.map((auth, i) => `  ${i + 1}. ${auth.name}\n     → ${auth.point}`),
      "",
      "KEY PRINCIPLES",
      ...note.keyPrinciples.map((p, i) => `  ${i + 1}. ${p}`),
      "",
      "OUTCOME",
      `  ${note.outcome}`,
      "",
      "STUDENT NOTES",
      `  ${note.studentNotes}`,
      "",
      "───────────────────────────────────────────────────────",
      "Generated by Ratio Moot Court. For educational purposes only.",
      "═══════════════════════════════════════════════════════",
    ];
    return lines.join("\n");
  };

  const handleCopy = async () => {
    if (!caseNote) return;
    try {
      await navigator.clipboard.writeText(generateTextVersion(caseNote));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = generateTextVersion(caseNote);
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    if (!caseNote) return;
    const text = generateTextVersion(caseNote);
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `case-note-${caseNote.caseName.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <>
      {/* Generate / View button */}
      {!caseNote && !isGenerating ? (
        <button
          onClick={onGenerate}
          className="flex items-center justify-center gap-2 w-full py-3 rounded-xl bg-navy-card border border-court-border text-court-sm text-court-text-sec hover:text-court-text hover:border-gold/40 transition-all"
        >
          <BookOpen size={16} />
          Generate Case Note
        </button>
      ) : isGenerating ? (
        <button
          disabled
          className="flex items-center justify-center gap-2 w-full py-3 rounded-xl bg-navy-card border border-court-border text-court-sm text-court-text-ter"
        >
          <Loader2 size={16} className="animate-spin" />
          Generating case note...
        </button>
      ) : caseNote ? (
        <button
          onClick={() => setIsOpen(true)}
          className="flex items-center justify-center gap-2 w-full py-3 rounded-xl bg-navy-card border border-gold/30 text-court-sm text-gold hover:bg-gold/5 transition-all"
        >
          <BookOpen size={16} />
          View Case Note
        </button>
      ) : null}

      {error && (
        <p className="text-court-xs text-red-400 text-center mt-1">{error}</p>
      )}

      {/* Slide-out panel */}
      <AnimatePresence>
        {isOpen && caseNote && (
          <>
            <motion.div
              className="fixed inset-0 bg-black/60 z-40"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsOpen(false)}
            />

            <motion.div
              className="fixed right-0 top-0 bottom-0 w-full max-w-lg bg-navy border-l border-court-border z-50 flex flex-col"
              initial={{ x: "100%" }}
              animate={{ x: 0 }}
              exit={{ x: "100%" }}
              transition={{ type: "spring", damping: 25, stiffness: 200 }}
            >
              {/* Header */}
              <div className="flex items-center justify-between px-4 py-3 border-b border-court-border-light shrink-0">
                <div>
                  <h3 className="font-serif text-court-base font-bold text-court-text">Case Note</h3>
                  <p className="text-court-xs text-court-text-ter">{caseNote.areaOfLaw}</p>
                </div>
                <div className="flex items-center gap-2">
                  <button onClick={handleCopy} className="p-2 rounded-lg hover:bg-white/5 transition-colors" title="Copy case note">
                    {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} className="text-court-text-ter" />}
                  </button>
                  <button onClick={handleDownload} className="p-2 rounded-lg hover:bg-white/5 transition-colors" title="Download case note">
                    <Download size={14} className="text-court-text-ter" />
                  </button>
                  <button onClick={() => setIsOpen(false)} className="p-2 rounded-lg hover:bg-white/5 transition-colors">
                    <X size={14} className="text-court-text-ter" />
                  </button>
                </div>
              </div>

              {/* Body */}
              <div className="flex-1 overflow-y-auto px-4 py-4 no-scrollbar">
                {/* Case header */}
                <div className="mb-5 pb-3 border-b border-court-border-light/50">
                  <p className="text-court-xs text-gold uppercase tracking-widest font-bold mb-1">
                    {caseNote.court}
                  </p>
                  <h4 className="font-serif text-lg font-bold text-court-text leading-snug">
                    {caseNote.caseName}
                  </h4>
                  <p className="text-court-xs text-court-text-ter mt-1">{caseNote.citation}</p>
                </div>

                {/* Parties */}
                <Section title="Parties">
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <p className="text-court-xs text-court-text-ter mb-0.5">Appellant/Claimant</p>
                      <p className="text-court-sm text-court-text">{caseNote.parties.appellant}</p>
                    </div>
                    <div>
                      <p className="text-court-xs text-court-text-ter mb-0.5">Respondent/Defendant</p>
                      <p className="text-court-sm text-court-text">{caseNote.parties.respondent}</p>
                    </div>
                  </div>
                </Section>

                {/* Legal Issues */}
                <Section title="Legal Issues">
                  {caseNote.legalIssues.map((issue, i) => (
                    <div key={i} className="flex gap-2 mb-2 last:mb-0">
                      <span className="text-court-xs text-gold font-bold shrink-0 mt-0.5">{i + 1}.</span>
                      <p className="text-court-sm text-court-text leading-relaxed">{issue}</p>
                    </div>
                  ))}
                </Section>

                {/* Arguments For */}
                <Section title="Arguments Advanced">
                  {caseNote.argumentsFor.map((arg, i) => (
                    <div key={i} className="flex gap-2 mb-2 last:mb-0">
                      <span className="text-court-xs text-green-400 shrink-0 mt-0.5">✓</span>
                      <p className="text-court-sm text-court-text leading-relaxed">{arg}</p>
                    </div>
                  ))}
                </Section>

                {/* Arguments Against */}
                <Section title="Counter-Arguments Raised">
                  {caseNote.argumentsAgainst.map((arg, i) => (
                    <div key={i} className="flex gap-2 mb-2 last:mb-0">
                      <span className="text-court-xs text-red-400 shrink-0 mt-0.5">✗</span>
                      <p className="text-court-sm text-court-text leading-relaxed">{arg}</p>
                    </div>
                  ))}
                </Section>

                {/* Authorities */}
                <Section title="Authorities Cited">
                  {caseNote.authoritiesCited.map((auth, i) => (
                    <div key={i} className="mb-3 last:mb-0 pl-3 border-l-2 border-gold/30">
                      <p className="text-court-sm font-bold text-court-text">{auth.name}</p>
                      <p className="text-court-xs text-court-text-sec mt-0.5">{auth.point}</p>
                    </div>
                  ))}
                </Section>

                {/* Key Principles */}
                <Section title="Key Principles">
                  {caseNote.keyPrinciples.map((p, i) => (
                    <div key={i} className="flex gap-2 mb-2 last:mb-0">
                      <span className="text-court-xs text-gold shrink-0 mt-0.5">§</span>
                      <p className="text-court-sm text-court-text leading-relaxed">{p}</p>
                    </div>
                  ))}
                </Section>

                {/* Outcome */}
                <Section title="Outcome">
                  <p className="text-court-sm text-court-text leading-relaxed">{caseNote.outcome}</p>
                </Section>

                {/* Student Notes */}
                <div className="mt-4 p-3 rounded-lg bg-gold/5 border border-gold/20">
                  <p className="text-court-xs text-gold uppercase tracking-widest font-bold mb-1.5">Revision Notes</p>
                  <p className="text-court-sm text-court-text leading-relaxed">{caseNote.studentNotes}</p>
                </div>

                <p className="text-court-xs text-court-text-ter text-center mt-4">
                  AI-generated for educational purposes. Verify against primary sources.
                </p>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </>
  );
}

// ── Section helper ──

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-4">
      <h5 className="text-court-xs text-court-text-ter uppercase tracking-widest font-bold mb-2">{title}</h5>
      {children}
    </div>
  );
}
