"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, X, Download, Copy, Check } from "lucide-react";

interface TranscriptMessage {
  role: "ai" | "user";
  text: string;
  time: string;
}

interface TranscriptPanelProps {
  messages: TranscriptMessage[];
  caseTitle: string;
  personaName: string;
  areaOfLaw: string;
}

/**
 * Court Transcript Panel — shows the session formatted like a real
 * court stenographer's output with speaker labels, paragraph numbers,
 * and timestamps. Can be copied or downloaded.
 */
export default function TranscriptPanel({
  messages,
  caseTitle,
  personaName,
  areaOfLaw,
}: TranscriptPanelProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateTranscriptText = () => {
    const header = [
      "═══════════════════════════════════════════════════════",
      "                 COURT TRANSCRIPT",
      "       Ratio — The Digital Court Society",
      "═══════════════════════════════════════════════════════",
      "",
      `Matter: ${caseTitle}`,
      `Area:   ${areaOfLaw}`,
      `Date:   ${new Date().toLocaleDateString("en-GB", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}`,
      `Before: ${personaName}`,
      "",
      "───────────────────────────────────────────────────────",
      "",
    ].join("\n");

    const body = messages
      .map((msg, i) => {
        const speaker = msg.role === "user" ? "COUNSEL" : "THE COURT";
        const paraNum = String(i + 1).padStart(3, " ");
        return `[${paraNum}] ${speaker} (${msg.time}):\n    ${msg.text}\n`;
      })
      .join("\n");

    const footer = [
      "",
      "───────────────────────────────────────────────────────",
      "End of transcript. Generated by Ratio Moot Court.",
      "For educational purposes only.",
      "═══════════════════════════════════════════════════════",
    ].join("\n");

    return header + body + footer;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateTranscriptText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = generateTranscriptText();
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    const text = generateTranscriptText();
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `ratio-transcript-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <>
      {/* Toggle button */}
      <button
        onClick={() => setIsOpen(true)}
        className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-navy-card border border-court-border text-court-xs text-court-text-ter hover:text-court-text transition-colors"
        title="View court transcript"
      >
        <FileText size={12} />
        <span className="hidden sm:inline">Transcript</span>
      </button>

      {/* Slide-out panel */}
      <AnimatePresence>
        {isOpen && (
          <>
            {/* Backdrop */}
            <motion.div
              className="fixed inset-0 bg-black/60 z-40"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsOpen(false)}
            />

            {/* Panel */}
            <motion.div
              className="fixed right-0 top-0 bottom-0 w-full max-w-md bg-navy border-l border-court-border z-50 flex flex-col"
              initial={{ x: "100%" }}
              animate={{ x: 0 }}
              exit={{ x: "100%" }}
              transition={{ type: "spring", damping: 25, stiffness: 200 }}
            >
              {/* Header */}
              <div className="flex items-center justify-between px-4 py-3 border-b border-court-border-light shrink-0">
                <div>
                  <h3 className="font-serif text-court-base font-bold text-court-text">Court Transcript</h3>
                  <p className="text-court-xs text-court-text-ter">{messages.length} entries</p>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopy}
                    className="p-2 rounded-lg hover:bg-white/5 transition-colors"
                    title="Copy transcript"
                  >
                    {copied ? (
                      <Check size={14} className="text-green-400" />
                    ) : (
                      <Copy size={14} className="text-court-text-ter" />
                    )}
                  </button>
                  <button
                    onClick={handleDownload}
                    className="p-2 rounded-lg hover:bg-white/5 transition-colors"
                    title="Download transcript"
                  >
                    <Download size={14} className="text-court-text-ter" />
                  </button>
                  <button
                    onClick={() => setIsOpen(false)}
                    className="p-2 rounded-lg hover:bg-white/5 transition-colors"
                  >
                    <X size={14} className="text-court-text-ter" />
                  </button>
                </div>
              </div>

              {/* Transcript body */}
              <div className="flex-1 overflow-y-auto px-4 py-4 no-scrollbar">
                {/* Case info header */}
                <div className="mb-4 pb-3 border-b border-court-border-light/50">
                  <p className="text-court-xs text-gold uppercase tracking-widest font-bold mb-1">
                    In the matter of
                  </p>
                  <p className="text-court-sm text-court-text leading-relaxed">{caseTitle}</p>
                  <p className="text-court-xs text-court-text-ter mt-1">Before: {personaName}</p>
                </div>

                {/* Messages */}
                {messages.map((msg, i) => (
                  <div key={i} className="mb-4">
                    <div className="flex items-baseline gap-2 mb-1">
                      <span className="text-court-xs text-court-text-ter font-mono w-6 shrink-0 text-right">
                        {i + 1}.
                      </span>
                      <span className={`text-court-xs font-bold uppercase tracking-wider ${
                        msg.role === "user" ? "text-gold" : "text-court-text-sec"
                      }`}>
                        {msg.role === "user" ? "Counsel" : "The Court"}
                      </span>
                      <span className="text-court-xs text-court-text-ter">
                        {msg.time}
                      </span>
                    </div>
                    <p className="text-court-sm text-court-text leading-relaxed pl-8">
                      {msg.text}
                    </p>
                  </div>
                ))}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </>
  );
}
